import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Pencil,
  Edit,
  Printer,
  DownloadCloud,
  Upload,
  Download,
  Calendar,
  FileUp,
  RefreshCw,
  Search,
  Building,
  Cable,
  Smartphone,
  Monitor,
  Headphones,
  BookOpen,
  Server,
  Lock,
  BadgeCheck,
  UserCheck,
  ShieldAlert,
  ShieldCheck,
  Bell,
  LogOut,
  Wrench,
  History,
  Receipt,
  Award,
  BarChart3,
  FileBarChart,
  LineChart,
  PieChart,
  Activity,
  UserCog,
  Users,
  QrCode,
  Compass,
  Boxes,
  Warehouse,
  FileArchive,
  Unlink,
  CreditCard as CreditCardIcon,
  LandPlot,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";

export const Icons = {
  add: Plus,
  arrowRight: ArrowRight,
  billing: CreditCard,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  command: Command,
  warning: AlertTriangle,
  user: User,
  x: X,
  spinner: Loader2,
  moon: Moon,
  sun: SunMedium,
  help: HelpCircle,
  post: FileText,
  page: File,
  settings: Settings,
  image: Image,
  pizza: Pizza,
  twitter: Twitter,
  trash: Trash,
  dots: MoreVertical,
  edit: Edit,
  pencil: Pencil,
  printer: Printer,
  download: Download,
  downloadCloud: DownloadCloud,
  upload: Upload,
  calendar: Calendar,
  fileUp: FileUp,
  refresh: RefreshCw,
  search: Search,
  building: Building,
  cable: Cable,
  smartphone: Smartphone,
  monitor: Monitor,
  laptop: Laptop,
  headphones: Headphones,
  book: BookOpen,
  server: Server,
  lock: Lock,
  badgeCheck: BadgeCheck,
  userCheck: UserCheck,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  notification: Bell,
  logout: LogOut,
  wrench: Wrench,
  history: History,
  receipt: Receipt,
  award: Award,
  chart: BarChart3,
  fileChart: FileBarChart,
  lineChart: LineChart,
  pieChart: PieChart,
  activity: Activity,
  userCog: UserCog,
  users: Users,
  qrcode: QrCode,
  compass: Compass,
  boxes: Boxes,
  warehouse: Warehouse,
  archive: FileArchive,
  unlink: Unlink,
  creditCard: CreditCardIcon,
  plus: Plus,
  land: LandPlot,
};